#name: craete jira issue
#on:
# issues:
#  types: [opened]
#  
#jobs:
#  create-issue:
#    name: create jira issue
#    runs-on: ubuntu-latest
#    steps:
#    - name: login
#      uses: atlassian/gajira-login@v3
#      env: 
#        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
#         JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
#         JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}        
#     - name: Create Issue 
#       uses: atlassian/gajira-create@v3
#       with:
#         project: MP 
#         issuetype: Task 
#         summary: '${{ github.event.issue.title }}'
#         description: '${{ github.event.issue.html_url }}'
